### ISSUE TITLE
Cannot reproduce kmeans results for Mocov2/SwAV

### ISSUE THREAD

**Issue by MkuuWaUjinga** [wvangansbeke/Unsupervised-Semantic-Segmentation#14]
Hi there, thank you for the interesting paper. I am currently looking into your results and failed to reproduce the K-Means results for baseline methods such as MoCov2 on Pascal val. 
Would it be possible for you to add the evaluation scripts for other methods than MaskContrast as well? From what I understand `segmentation/kmeans.py` only works for MaskContrast as you use the saliency head to seperate fg from bg vectors.

**Comment by wvangansbeke** [comment]
Hi @MkuuWaUjinga,

To evaluate the representation we simply clustered the features in the bottleneck (see Supplementary). Should not be that difficult to run if you have enough memory.

**Comment by MkuuWaUjinga** [comment]
Thanks for your response :) 
Do you do PCA on the layer4-features as well as you do for MaskContrast? If yes, what dimension?

**Comment by wvangansbeke** [comment]
Hi @MkuuWaUjinga,

Yes you can use the same dimension. I remember I tried different ones, but didn't change the results much.
