### ISSUE TITLE
Inference on trained model to generate unsupervised segmentation maps on any dataset

### ISSUE THREAD

**Issue by ramprs** [wvangansbeke/Unsupervised-Semantic-Segmentation#15]
Hi, could you please tell me how I can just run inference given a folder containing raw images to create segmentation maps? Do I just forward the images through the model and get a `(batch_size x 32 x 512 x 512)` output and then do argmax along the `32` dimension for each image? 

Thanks in advance

**Comment by wvangansbeke** [comment]
Hi @ramprs,

We evaluate the represenations in various ways: (1) applying K-means, (2) training a single 1x1 convolution layer and (3) using a kNN-classifier (segment retrieval). You can find the exact evaluation procedure in the `segmentation` directory, (e.g., `segmentation/kmeans.py` for K-means).
