### ISSUE TITLE
Semantic Segment Retrieval for MoCo

### ISSUE THREAD

**Issue by Yingdong-Hu** [wvangansbeke/Unsupervised-Semantic-Segmentation#19]
Hi @wvangansbeke
Thank you for sharing such a great job !

I want to know how can I use MoCo v2 in the semantic segment retrieval task ?

For MaskContrast, you predict a salient object mask by using one layer convolutional head, then you can compute a feature vector by averaging the pixel embeddings within the predicted mask.

But for MoCo, there is no convolutional head used to obtain the salient mask, so how can I get the 48.0 mIoU results in Table 4 ?

**Comment by wvangansbeke** [comment]
Hi @Alxead,

Indeed. MoCo does not pretrain a decoder. We simply cluster the obtained grid before the average pooling layer in ResNet. The grid can have different sizes depending on the dilation rate you're using.
