### ISSUE TITLE
About trainaug.txt

### ISSUE THREAD

**Issue by oldfemalepig** [wvangansbeke/Unsupervised-Semantic-Segmentation#20]
Thank you for sharing such a great job !
I'm more concerned with the processing of the data.
How are ”saliency_supervised_model“ and ”SegmentationClassAug“ obtained in pascal_VOC.tgz?
And, I would like to ask how the “trainaug.txt” was obtained, I want to try to use this method on the custom dataset.
Thanks!

**Comment by wvangansbeke** [comment]
Hi @oldfemalepig,

- Please check the paper and the `saliency` directory in this repo for more details.
- The `trainaug` split on PASCAL is commonly used for semantic segmentation. It contains around 10k images.
