### ISSUE TITLE
request your weight

### ISSUE THREAD

**Issue by wuleibegreat** [wvangansbeke/Unsupervised-Semantic-Segmentation#21]
Thank you very much for your outstanding work about MaskConst.  I request to use your weight to carry out some of my other research, thank you very much.

**Comment by wvangansbeke** [comment]
Hi,

Models are released. See Model Zoo in Readme.

**Comment by wuleibegreat** [comment]
> 
hi
Google Cloud Disk shows that I do not have permission to download and need to apply

**Comment by wuleibegreat** [comment]
![微信图片_20211115150750](https://user-images.githubusercontent.com/55038618/146635819-d2bf293e-f514-4c9e-a64a-aa714f55a7b0.jpg)

**Comment by wuleibegreat** [comment]
![微信图片_20211218170750](https://user-images.githubusercontent.com/55038618/146635845-0b5e9bd7-8b09-4bb4-93a2-d8a12b47cbbd.png)

**Comment by wuleibegreat** [comment]
my google cloud account is  wuleisdunudt@gmail.com thank you very mush

**Comment by wvangansbeke** [comment]
Hi @wuleibegreat,

Can you download it now? Not sure what caused it.

**Comment by wuleibegreat** [comment]
@wvangansbeke  It's okay now, thank you very much for your work and wish you all the best
