### ISSUE TITLE
Possibly corrupt weight files

### ISSUE THREAD

**Issue by yanivnik** [wvangansbeke/Unsupervised-Semantic-Segmentation#22]
Hey,
First of all - Thanks for sharing your great work.

I tried downloading the weight files to play around with the code, but It seems all 4 tar files are corrupt - 
For example, when trying to open with the ZipExtractor straight from Google drive - 
![image](https://user-images.githubusercontent.com/7485871/147887376-ebf8c0c8-8d62-400d-92ab-38b85a61a13b.png)

or when opening via tar - 
![image](https://user-images.githubusercontent.com/7485871/147887415-d041e47d-b1dc-4aa8-b955-51605f7e7c5b.png)

Also failed to open via WinRAR 

Is it possible to check this out?

**Comment by wvangansbeke** [comment]
Hi @yanivnik,

You don't need to untar.
