### ISSUE TITLE
Linear evaluation protocols

### ISSUE THREAD

**Issue by donglao** [wvangansbeke/Unsupervised-Semantic-Segmentation#23]
Greetings,

I have a question regarding linear evaluation. It is my understanding that during evaluation, the model loads weights from both pre-trained encoder and pre-trained Deeplab head (that predicts saliency), then re-initialize and finetunes the last linear layer of Deeplab for semantic segmentation. When comparing with MOCO-V2 pre-trained weights, how do you initialize weights for the Deeplab head?

Thanks,
Lao

**Comment by wvangansbeke** [comment]
Hi @donglao,

I believe the discussion in issue #7 should be helpful (and possibly issue #19). In short, we only trained a 1x1 conv on top of a dilated ResNet backbone since MoCo does not pretrain a decoder. This gives quite good results.

**Comment by donglao** [comment]
Thank you for clarification
