### ISSUE TITLE
Question about feature transferability compared to supervised approaches

### ISSUE THREAD

**Issue by GerardMaggiolino** [wvangansbeke/Unsupervised-Semantic-Segmentation#26]
Were any experiments ran to evaluate how well representations learned by the model transfer to different datasets under linear eval in comparison to features learned by fully supervised counterparts? This is a nice property of self supervised image level representations, so I’m wondering if the same applies here. 

Awesome paper btw, looking forward to using it in my work 🙂

**Comment by wvangansbeke** [comment]
Hi @GerardMaggiolino,

Thank you for the kind words.
Yes. Transfer results from ImageNet to PASCAL, COCO and DAVIS can be found in Table 5 of the paper.
