### ISSUE TITLE
hi，About  dataset problem

### ISSUE THREAD

**Issue by yangkunhub** [wvangansbeke/Unsupervised-Semantic-Segmentation#28]
hello，I'm trying to implement the code，but 
PASCAL_VOC.tgz (1.9G) can't download from drive.google.com，Can you offer another way to download it.

**Comment by yangkunhub** [comment]
this is my email address 1332832532@qq.com

**Comment by 116022017144** [comment]
hello,friend,Do you solve the question?I meet the same problem.

**Comment by wvangansbeke** [comment]
Hi, 

The link provided in the README doesn't work for you? (see [here](https://drive.google.com/file/d/1pxhY5vsLwXuz6UHZVUKhtb7EJdCg2kuH/view)). It does work for me.

**Comment by 116022017144** [comment]
OK，I will try it



---Original---
From: "Wouter Van ***@***.***&gt;
Date: Fri, Jul 29, 2022 16:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wvangansbeke/Unsupervised-Semantic-Segmentation] hi，About  dataset problem (Issue #28)




 
Hi,
 
The link provided in the README doesn't work for you? (see here). It does work for me.

**Comment by 116022017144** [comment]
thanks



---Original---
From: "Wouter Van ***@***.***&gt;
Date: Fri, Jul 29, 2022 16:43 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wvangansbeke/Unsupervised-Semantic-Segmentation] hi，About  dataset problem (Issue #28)




 
Hi,
 
The link provided in the README doesn't work for you? (see here). It does work for me.
