### ISSUE TITLE
Issue in random augmentations to produce key and query

### ISSUE THREAD

**Issue by silky1708** [wvangansbeke/Unsupervised-Semantic-Segmentation#29]
https://github.com/wvangansbeke/Unsupervised-Semantic-Segmentation/blob/dfd5fa0a1542f2b26824b4059bd2bb1240c5c94b/pretrain/data/dataloaders/dataset.py#L93

Hi,
I may be wrong, but I am doubtful about line 93 in `DatasetKeyQuery` where you take two random augmentations of the `sample_` coming from `base_dataset`. `sample_` is a dictionary, containing the `image` and saliency map `sal`.
How do you maintain the correspondence between `image` and `sal` after the transformations?

When I'm using my own custom dataset, I find discrepancy in the `image` and `sal`(the saliency map is transformed in a way different from the `image`).

Thanks.

**Comment by wvangansbeke** [comment]
Hi @silky1708,

Have a look at [this file](https://github.com/wvangansbeke/Unsupervised-Semantic-Segmentation/blob/dfd5fa0a1542f2b26824b4059bd2bb1240c5c94b/pretrain/data/dataloaders/transforms.py). We transform the image and saliency jointly (e.g., if we flip the image, we also flip the saliency map).

**Comment by silky1708** [comment]
Thank you. Got it.
