### ISSUE TITLE
How to evaluate on DAVIS16?

### ISSUE THREAD

**Issue by blessingforever** [wvangansbeke/Unsupervised-Semantic-Segmentation#4]
Thanks for sharing your amazing work! And I wonder how the model can be used in DAVIS16?

**Comment by wvangansbeke** [comment]
Hi @blessingforever,

Thank you for your interest. Sorry for the late reply.
We adopt the evaluation protocol from Jabri et al. ("Space-time correspondence as a contrastive random walk"). The labels are propagated using nearest neighbors between consecutive frames.

**Comment by wvangansbeke** [comment]
For more information, see issue #5.
