### ISSUE TITLE
More Experimental Setup on DAVIS

### ISSUE THREAD

**Issue by Yingdong-Hu** [wvangansbeke/Unsupervised-Semantic-Segmentation#5]
Thank you for sharing such a great job ! 
Can you share more details about how to do label propagation on DAVIS (such as hyper-parameters you use)?
I notice that Contrastive Random Walk use the penultimate residual block as the embedding, so which layer do you use to perform label propagation ?

**Comment by wvangansbeke** [comment]
Hi @Alxead,

Thank you for your interest.
Yes. For Davis 2016, we adopt the evaluation protocol from Jabri et al. ("Space-time correspondence as a contrastive random walk").  The labels are propagated using nearest neighbors between consecutive frames. We used the same layer for the embeddings.

**Comment by Yingdong-Hu** [comment]
Does the same layer means the penultimate residual block ?

**Comment by wvangansbeke** [comment]
Yes after the 3rd ResNet-block if I remember correctly. They have the code on github, so you can check it. We simply used the publicly available code.

**Comment by Yingdong-Hu** [comment]
Thank you very much
