### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by zjy9779** [wvangansbeke/Unsupervised-Semantic-Segmentation#6]
cd segmentation
python eval.py --config_env configs/env.yml --config_exp configs/VOCSegmentation_supervised_saliency_model.yml --state-dict $PATH_TO_MODEL

In this step,  ,there is not "VOCSegmentation_supervised_saliency_model.yml" in segmentation/configs/, I copy this from "pretrain/configs/"

And I set --state-dict to the pretrained supervised model in MODEL ZOO, but got this problem. 

Retrieve model
Traceback (most recent call last):
  File "eval.py", line 63, in <module>
    main()
  File "eval.py", line 38, in main
    model = get_model(p)
  File "/media/yangxilab/media/zjy/seg21/Unsupervised-Semantic-Segmentation-main/segmentation/utils/common_config.py", line 89, in get_model
    load_pretrained_weights(p, model)
  File "/media/yangxilab/media/zjy/seg21/Unsupervised-Semantic-Segmentation-main/segmentation/utils/common_config.py", line 16, in load_pretrained_weights
    print('Loading pre-trained weights from {}'.format(p['pretraining']))
KeyError: 'pretraining'

thanks for your reply.

**Comment by wvangansbeke** [comment]
Hi @zjy9779,

Thank you for your interest.

Did you try: `cd segmentation &&
python linear_finetune.py --config_env configs/env.yml --config_exp configs/linear_finetune/linear_finetune_VOCSegmentation_supervised_saliency.yml`?
I added it to the README.

**Comment by zjy9779** [comment]
> Hi @zjy9779,
> 
> Thank you for your interest.
> 
> Did you try: `cd segmentation && python linear_finetune.py --config_env configs/env.yml --config_exp configs/linear_finetune/linear_finetune_VOCSegmentation_supervised_saliency.yml`?
> I added it to the README.

Yes, I downloaded the dataset and followed your every step yesterday, but it still have problems in run eval.py.

**Comment by wvangansbeke** [comment]
Hi @zjy9779,

So what do you get now? `pretraining` is defined in `configs/linear_finetune/linear_finetune_VOCSegmentation_supervised_saliency.yml`. For me this works.

**Comment by zjy9779** [comment]
> Hi @zjy9779,
> 
> So what do you get now? `pretraining` is defined in `configs/linear_finetune/linear_finetune_VOCSegmentation_supervised_saliency.yml`. For me this works.

**Now I run**
python eval.py --config_env configs/env.yml --config_exp configs/linear_finetune/linear_finetune_VOCSegmentation_supervised_saliency.yml --state-dict ./results1/linear_finetune_VOCSegmentation_supervised_saliency/checkpoint.pth.tar

**got**

Loading state dict from checkpoint
Warning: This piece of code was only tested for linear classification
Warning: Assertions should probably depend on model type (Segm/ContrastiveSegm)
Traceback (most recent call last):
  File "eval.py", line 63, in <module>
    main()
  File "eval.py", line 38, in main
    model = get_model(p)
  File "Unsupervised-Semantic-Segmentation-main/segmentation/utils/common_config.py", line 89, in get_model
    load_pretrained_weights(p, model)
  File "Unsupervised-Semantic-Segmentation-main/segmentation/utils/common_config.py", line 31, in load_pretrained_weights
    assert(set(msg[0]) == set(['decoder.4.weight', 'decoder.4.bias']))
AssertionError


**In addiction,  when I run** 
python retrieval.py --config_env configs/env.yml --config_exp configs/retrieval/retrieval_VOCSegmentation_unsupervised_saliency.yml 

**I got** 

mIoU is 3.76
IoU class background is 78.91
IoU class aeroplane is 0.00
IoU class bicycle is 0.00
IoU class bird is 0.00
IoU class boat is 0.00
IoU class bottle is 0.00
IoU class bus is 0.00
IoU class car is 0.00
IoU class cat is 0.00
IoU class chair is 0.00
IoU class cow is 0.00
IoU class diningtable is 0.00
IoU class dog is 0.00
IoU class horse is 0.00
IoU class motorbike is 0.00
IoU class person is 0.00
IoU class pottedplant is 0.00
IoU class sheep is 0.00
IoU class sofa is 0.00
IoU class train is 0.00
IoU class tvmonitor is 0.00

**I set** "pretraining:" "Unsupervised-Semantic-Segmentation-main/VOCSegmentation_unsupervised_saliency_model.pth.tar"   **in retrieval_VOCSegmentation_unsupervised_saliency.yml.**

**Comment by xielu6** [comment]
My IoU is also 0.00, How can I solve this problem?

**Comment by wvangansbeke** [comment]
I will double check this, but it looks like the model is not loaded properly.

**Comment by wvangansbeke** [comment]
Hi @xielu6, @zjy9779 

I took a quick look. Check out my log file (`out.txt`) underneath. As you can see I don't get the assertion error. Are you sure it loads the correct model? The arguments in the log file should help you out further.

``` 
python eval.py --config_env configs/env.yml --config_exp configs/linear_finetune/linear_finetune_VOCSegmentation_supervised_saliency.yml --state-dict $MODEL_PATH >> out.txt
```
The file `out.txt` can be found here: [out.txt](https://github.com/wvangansbeke/Unsupervised-Semantic-Segmentation/files/6985309/out.txt)

I hope this is helpful.

**Comment by esizikova** [comment]
I am having the same issue. My log file looks very similar but when I run:                                                                         `python eval.py --config_env configs/env.yml --config_exp configs/linear_finetune/linear_finetune_VOCSegmentation_supervised_saliency.yml --state-dict pretrained/github/linear_finetune_VOCSegmentation_supervised_saliency/best_model.pth.tar`

I get
mIoU is 10.69
IoU class background is 76.09
IoU class aeroplane is 1.82
IoU class bicycle is 10.74
IoU class bird is 15.22
IoU class boat is 0.05
IoU class bottle is 25.17
IoU class bus is 1.59
IoU class car is 7.79
IoU class cat is 24.67
IoU class chair is 6.36
IoU class cow is 0.00
IoU class diningtable is 0.00
IoU class dog is 13.64
IoU class horse is 0.06
IoU class motorbike is 0.07
IoU class person is 21.28
IoU class pottedplant is 6.44
IoU class sheep is 0.00
IoU class sofa is 9.11
IoU class train is 1.03
IoU class tvmonitor is 3.43

**Comment by wvangansbeke** [comment]
Hi @esizikova @xielu6 @zjy9779,

I just tested it again from scratch and followed the steps 1-6:

1) Clone the repo and go to the segmentation dir: `cd segmentation`
2) Download the pretrained model and linear finetuned model (see README) to the  `segmentation` dir.
3) Adapt the path in `data/utils/mypath.py` to the location of the PASCAL dataset.
4) Set output directory in `configs/env.yml` to your desired location.
5) In `configs/linear_finetune/linear_finetune_VOCSegmentation_supervised_saliency.yml` set `pretraining: 'VOCSegmentation_supervised_saliency_model.pth.tar'` (pretrained model)
6) Now, run ` python eval.py --config_env configs/env.yml --config_exp configs/linear_finetune/linear_finetune_VOCSegmentation_supervised_saliency.yml --state_dict linear_finetune_VOCSegmentation_supervised_saliency.pth.tar` if you want to obtain the final results.

This worked for me since I got the reported 63.9% from in the paper again. So can you try these steps?

**Comment by esizikova** [comment]
Thank you! I resolved it after checking that the python dependencies had the correct version (I think the issue was newer pytorch doesn't work). But 1.5 does.

**Comment by wvangansbeke** [comment]
Hi @esizikova 

Thanks for letting me know. I will add this note to the readme.

@xielu6 @zjy9779 Pytorch 1.5 should work as @esizikova pointed out. Thanks for the effort.
