### ISSUE TITLE
MaskContrast (IN Sup. Init. + Unsup. Sal.) pretrained model

### ISSUE THREAD

**Issue by AhmetSencan** [wvangansbeke/Unsupervised-Semantic-Segmentation#8]
Hi @wvangansbeke,
Can you please also share the pretrained model for MaskContrast (IN Sup. Init. + Unsup. Sal.)?

**Comment by wvangansbeke** [comment]
Hi @AhmetSencan,

I appreciate the interest.
Is it possible to train it yourself? I'm on vacation now. Should be fairly easy since we provide the config files and models already for the other settings. Should give you around 61.0% when finetuning a linear classifier on top.

**Comment by AhmetSencan** [comment]
Oh, okay. I will give it a try. Thank you for the answer.
